version: "3.4"

services:
  store-pages:
    build: store-pages
    image: store-pages
    restart: unless-stopped
    volumes:
      - ./store-pages/:/app
    ports:
      - 7777:7777
    depends_on:
      - database
      - flyway
    env_file:
      - project.env

  database:
    container_name: database-p1-3669f4dc-5e14-4733-8b72-2d59122fe97a
    image: "postgres:13.4"
    restart: "unless-stopped"
    env_file:
      - project.env

  flyway:
    image: flyway/flyway:9.11.0-alpine
    depends_on:
      - database
    volumes:
      - .:/flyway/sql
    command: -connectRetries=60 -baselineOnMigrate=true migrate
    env_file:
      - project.env

  e2e-playwright:
    entrypoint: "/bin/true" # Prevent startup on docker-compose up
    build: e2e-playwright
    image: e2e-playwright
    network_mode: host
    depends_on:
      - store-pages
    volumes:
      - ./e2e-playwright/tests:/e2e-playwright/tests